forge 'http://forge.puppetlabs.com/'

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apt'
mod 'puppetlabs/mysql'
mod 'attachmentgenie/ssh'
mod 'jfryman/nginx'
mod 'torrancew/account'
mod 'saz/ntp'
mod 'saz/sudo'
