#!/bin/bash
set -eu

if ! which bundler; then
  apt-get update -qq
  apt-get install -qqy --no-reinstall bundler build-essential
fi

cd "$(dirname $0)/.."
bundle install --path vendor/bundle
bundle exec puppet apply \
  --modulepath=modules:vendor/modules \
  --manifestdir=manifests \
  --hiera_config=hiera.yaml \
  --detailed-exitcodes \
  --verbose \
  "$@" \
  manifests/site.pp || [ $? -eq 2 ]
exit $?
