#!/bin/bash
set -eu

if ! which puppet; then
  apt-get install -qqy --no-reinstall ruby1.9.1 puppet hiera
fi

if ! gem list -i hiera-gpg; then
  apt-get install -qqy --no-reinstall ruby1.9.1-dev
  gem install --no-ri --no-rdoc hiera-gpg
fi

cd "$(dirname $0)/.."
puppet apply \
  --modulepath=modules:vendor/modules \
  --manifestdir=manifests \
  --hiera_config=hiera.yaml \
  --detailed-exitcodes \
  --verbose \
  "$@" \
  manifests/site.pp || [ $? -eq 2 ]
exit $?
